context:
  name: libsolv
  version: "0.7.14"
  sha256: 34a67c23cedd38a949607d8cdbd867aa4b07556f18a57e17162ac962bbdbbf54

package:
  name: "{{ name | lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/openSUSE/libsolv/archive/{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 3
  skip: 
    - win and vc<14
  run_exports:
    - "{{ pin_subpackage(name, max_pin='x.x') }}"

outputs:
  - package:
      name: libsolv
    # build:
      # need to find a way to express this!
      # script: install.sh  # [unix]
      # script: build.sh
    requirements:
      build:
        - "{{ compiler('c') }}"
        - "{{ compiler('cxx') }}"
        - sel(not win): make
        - sel(win): ninja
        - cmake
      host:
        - zlib
    test:
      commands:
        # - test -f ${PREFIX}/lib/libsolv${SHLIB_EXT}  # [unix]
        # - test -f ${PREFIX}/lib/libsolvext${SHLIB_EXT}  # [unix]
        # - test -f ${PREFIX}/lib/libsolv.so.1  # [linux]
        # - test -f ${PREFIX}/include/solv/repo.h  # [unix]
        # - if exist %LIBRARY_INC%\solv\repo.h (exit 0) else (exit 1)  # [win]
        # - if exist %LIBRARY_LIB%\solv.lib (exit 0) else (exit 1)  # [win]
        # - if exist %LIBRARY_LIB%\solvext.lib (exit 0) else (exit 1)  # [win]
        # - if exist %LIBRARY_BIN%\solv.dll (exit 0) else (exit 1)  # [win]
        # - dumpsolv.exe -h  # [win]
        - sel(unix): dumpsolv -h

about:
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
