context:
    version: "4.2.1"

package:
  name: octave
  version: "{{ version }}"

source:
  url: https://ftp.gnu.org/gnu/octave/octave-{{ version }}.tar.gz
  sha256: 80c28f6398576b50faca0e602defb9598d6f7308b0903724442c2a35a605333b
  patches:
    # patches taken from macports
    # https://github.com/macports/macports-ports/tree/master/math/octave/files
    # Link fails with undefined symbol ~file_stat
    - patch-file-stat.cc.diff
    # qscintilla2 library is not found without this
    - patch-qscintilla2.diff

build:
  number: 15
  skip:
    - win
  detect_binary_files_with_prefix: False

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - sed
    - perl
    - sel(linux): pkg-config
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
    - sel(linux): "{{ cdt('expat') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxrender') }}"
    - sel(linux): "{{ cdt('libxt') }}"
    - sel(linux): "{{ cdt('libxft') }}"
    - sel(linux): "{{ cdt('libx11-devel') }}"
    - sel(linux): "{{ cdt('xorg-x11-proto-devel') }}"
  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - pcre
    - readline
    - arpack
    - curl
    - fftw
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - suitesparse
    - zlib
    - bzip2
    - portaudio
    - libsndfile
    - qscintilla2
    - qhull
    - sel(linux): graphicsmagick
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt 5.9
    - openssl
  run:
    - pcre
    - readline
    - arpack
    - curl
    - '{{ pin_compatible("fftw", max_pin="x.x") }}'
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - hdf5
    - '{{ pin_compatible("suitesparse", max_pin="x.x") }}'
    - zlib
    - bzip2
    - '{{ pin_compatible("portaudio") }}'
    - libsndfile
    - '{{ pin_compatible("qscintilla2", max_pin="x.x") }}'
    - qhull
    - sel(linux): "{{ pin_compatible('graphicsmagick') }}"
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt
    - openssl

test:
  requires:
    - coreutils
  commands:
    - octave --version
    - touch test_file.txt
    - octave test_file.txt

about:
  home: https://www.gnu.org/software/octave/
  license: GPL-3.0-or-later
  license_file: COPYING
  doc_url: https://www.gnu.org/software/octave/doc/interpreter/
  summary: 'GNU Octave is a high-level language, primarily intended for numerical computations'

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
