name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Install micromamba
      shell: bash -l {0}
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
        else
          wget -qO- https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
          mv bin/micromamba ./micromamba
        fi
        ./micromamba shell init -s bash -p ~/micromamba
        mkdir -p ~/micromamba/pkgs/

    - name: Mamba create env
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export MAMBA_EXE=$(pwd)/micromamba
        . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
        ./micromamba create -f ./tests/env.yml -y

    - name: Install boa
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export MAMBA_EXE=$(pwd)/micromamba
        . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
        micromamba activate test

        pip install .

    - name: Run tests
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export MAMBA_EXE=$(pwd)/micromamba
        . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
        micromamba activate test

        pytest tests
